# networks:
  # media:
    # external: true
    # name: media_net
    # driver: bridge
    # attachable: true
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined # optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=${UMASK_SET}
    volumes:
      - ${STACK_CONFIG_DIR}/calibre:/config
      - ${STACK_MEDIA_ROUTE_EBOOKS}:/ebooks        # Ruta a la librería de ebooks
      - ${STACK_EBOOKS_IMPORT_DIR}:/ebooks-import  #Capeta para importar ebooks automáticamente a la librería.
    restart: unless-stopped
    ports:
      - 8080:8080
      - 8181:8181
      - 8081:8081
    # networks:
      # - media
