services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined # optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=${UMASK_SET}
    volumes:
      - ${STACK_CONFIG_DIR}/calibre:/config
      - ${STACK_MEDIA_ROUTE_EBOOKS}:/ebooks        # Ruta a la librería de ebooks
      - ${STACK_EBOOKS_IMPORT_DIR}:/ebooks-import  #Capeta para importar ebooks automáticamente a la librería.
    restart: unless-stopped
    ports:
      - 8080:8080
      - 8181:8181
      - 8081:8081
    networks:
      homemediaforge_net:
        ipv4_address: ${CALIBRE_IPV4:-172.30.0.34}

networks:
  homemediaforge_net:
    name: ${HOMEMEDIAFORGE_NET_NAME:-homemediaforge_net}
    driver: bridge
    ipam:
      config:
        - subnet: ${HOMEMEDIAFORGE_NET_SUBNET:-172.30.0.0/24}
