services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    hostname: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STACK_CONFIG_DIR}/lidarr:/config
      - ${STACK_MEDIA_ROUTE_MUSIC}:/music
      - ${STACK_DOWNLOADS_DIR_COMPLETED}:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lidarr.rule=Host(`${LIDARR_TRAEFIK_HOST:-lidarr}.${TRAEFIK_LOCAL_DOMAIN:-local}`) || Host(`${LIDARR_TRAEFIK_HOST:-lidarr}.${HOSTNAME:-homemediaforge}.${TRAEFIK_LOCAL_DOMAIN:-local}`)"
      - "traefik.http.routers.lidarr.entrypoints=https"
      - "traefik.http.services.lidarr.loadbalancer.server.port=8686"
    depends_on:
      - traefik
    ports:
      - ${LIDARR_PORT:-8686}:8686
    restart: unless-stopped
    networks:
      homemediaforge_net:
        ipv4_address: ${LIDARR_IPV4:-172.30.0.38}

networks:
  homemediaforge_net:
    name: ${HOMEMEDIAFORGE_NET_NAME:-homemediaforge_net}
    driver: bridge
    ipam:
      config:
        - subnet: ${HOMEMEDIAFORGE_NET_SUBNET:-172.30.0.0/24}
