services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    hostname: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${STACK_CONFIG_DIR}/overseer:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`${OVERSEERR_TRAEFIK_HOST:-overseerr}.${TRAEFIK_LOCAL_DOMAIN:-local}`)"
      - "traefik.http.routers.overseerr.entrypoints=https"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
    ports:
      - ${OVERSEERR_PORT:-5055}:5055
    restart: unless-stopped
    networks:
      homemediaforge_net:
        ipv4_address: ${OVERSEERR_IPV4:-172.30.0.39}

networks:
  homemediaforge_net:
    name: ${HOMEMEDIAFORGE_NET_NAME:-homemediaforge_net}
    driver: bridge
    ipam:
      config:
        - subnet: ${HOMEMEDIAFORGE_NET_SUBNET:-172.30.0.0/24}
