# networks:
  # media:
    # external: true
    # name: media_net
    # driver: bridge
    # attachable: true

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    hostname: ${HOSTNAME}
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES}
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=${VERSION}
      - TZ=${TZ}
    volumes:
      - ${STACK_CONFIG_DIR}/plex_library:/config
      - ${STACK_MEDIA_ROUTE_MOVIES}:/movies
      - ${STACK_MEDIA_ROUTE_TV}:/tv
      - ${STACK_MEDIA_ROUTE_ANIME}:/anime
      - ${STACK_MEDIA_ROUTE_MUSIC}:/music
      - ${STACK_MEDIA_ROUTE_CONCERTS}:/concerts
      - ${STACK_MEDIA_TRANSCODE_DIR}:/transcode
    ports:
      - ${PLEX_PORT:-32400}:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    restart: unless-stopped
    # networks:
      # - media
