services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STACK_CONFIG_DIR}/radarr:/config
      - ${STACK_MEDIA_ROUTE_MOVIES}:/movies
      - ${STACK_MEDIA_ROUTE_CONCERTS}:/concerts
      - ${STACK_DOWNLOADS_DIR_COMPLETED}:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`${RADARR_TRAEFIK_HOST:-radarr}.${TRAEFIK_LOCAL_DOMAIN:-local}`) || Host(`${RADARR_TRAEFIK_HOST:-radarr}.${HOSTNAME:-homemediaforge}.${TRAEFIK_LOCAL_DOMAIN:-local}`)"
      - "traefik.http.routers.radarr.entrypoints=https"
      - "traefik.http.routers.radarr.tls.certresolver=hmf"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    depends_on:
      - traefik
    ports:
      - ${RADARR_PORT:-7878}:7878
    restart: unless-stopped
    networks:
      homemediaforge_net:
        ipv4_address: ${RADARR_IPV4:-172.30.0.41}

networks:
  homemediaforge_net:
    name: ${HOMEMEDIAFORGE_NET_NAME:-homemediaforge_net}
    driver: bridge
    ipam:
      config:
        - subnet: ${HOMEMEDIAFORGE_NET_SUBNET:-172.30.0.0/24}
