services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STACK_CONFIG_DIR}/radarr:/config
      - ${STACK_MEDIA_ROUTE_MOVIES}:/movies
      - ${STACK_MEDIA_ROUTE_CONCERTS}:/concerts
      - ${STACK_DOWNLOADS_DIR_COMPLETED}:/downloads
    ports:
      - ${RADARR_PORT:-7878}:7878
    restart: unless-stopped
    networks:
      homemediaforge_net:
        ipv4_address: 172.30.0.41

networks:
  homemediaforge_net:
    name: homemediaforge_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
