services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STACK_CONFIG_DIR}/sonarr:/config
      - ${STACK_MEDIA_ROUTE_TV}:/tv
      - ${STACK_DOWNLOADS_DIR_COMPLETED}:/downloads
    ports:
      - ${SONARR_PORT:-8989}:8989
    restart: unless-stopped
    networks:
      homemediaforge_net:
        ipv4_address: 172.30.0.42

networks:
  homemediaforge_net:
    name: homemediaforge_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
