services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STACK_CONFIG_DIR}/sonarr:/config
      - ${STACK_MEDIA_ROUTE_TV}:/tv
      - ${STACK_DOWNLOADS_DIR_COMPLETED}:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`${SONARR_TRAEFIK_HOST:-sonarr}.${TRAEFIK_LOCAL_DOMAIN:-local}`) || Host(`${SONARR_TRAEFIK_HOST:-sonarr}.${HOSTNAME:-homemediaforge}.${TRAEFIK_LOCAL_DOMAIN:-local}`)"
      - "traefik.http.routers.sonarr.entrypoints=https"
      - "traefik.http.routers.sonarr.tls.certresolver=hmf"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    depends_on:
      - traefik
    ports:
      - ${SONARR_PORT:-8989}:8989
    restart: unless-stopped
    networks:
      homemediaforge_net:
        ipv4_address: ${SONARR_IPV4:-172.30.0.42}

networks:
  homemediaforge_net:
    name: ${HOMEMEDIAFORGE_NET_NAME:-homemediaforge_net}
    driver: bridge
    ipam:
      config:
        - subnet: ${HOMEMEDIAFORGE_NET_SUBNET:-172.30.0.0/24}
