networks:
  media:
    external: true
    name: media_net
    driver: bridge
    attachable: true

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STACK_CONFIG_DIR}/sonarr:/config
      - ${STACK_MEDIA_ROUTE_TV}:/tv
      - ${STACK_DOWNLOADS_DIR_COMPLETED}:/downloads
    restart: unless-stopped
    networks:
      - media
