services:
  whisparr:
    image: ghcr.io/thespad/whisparr:latest
    container_name: whisparr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STACK_CONFIG_DIR}:/config
      - ${STACK_DOWNLOADS_DIR_COMPLETED}:/downloads
      - ${STACK_MEDIA_ROUTE_ADULT}:/movies # Carpeta personalizada para Whisparr
    ports:
      - ${WHISPARR_PORT:-6969}:6969
    restart: unless-stopped
    networks:
      homemediaforge_net:
        ipv4_address: 172.30.0.43

networks:
  homemediaforge_net:
    name: homemediaforge_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
