services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    restart: unless-stopped
    network_mode: "host" # se mantiene para banear
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=${TZ}
      - F2B_LOG_LEVEL=INFO
      - F2B_LOG_TARGET=STDOUT
      - F2B_RESTART_ALWAYS=true
    volumes:
      - ${STACK_CONFIG_DIR}/fail2ban/etc/fail2ban/jail.local:/etc/fail2ban/jail.local:ro
      - ${STACK_CONFIG_DIR}/fail2ban/etc/fail2ban/filter.d/nginx-http-auth.conf:/etc/fail2ban/filter.d/nginx-http-auth.conf:ro
      - ${STACK_CONFIG_DIR}/fail2ban/etc/fail2ban/filter.d/nginx-radarr-login.conf:/etc/fail2ban/filter.d/nginx-radarr-login.conf:ro
      - ${STACK_CONFIG_DIR}/fail2ban/etc/fail2ban/filter.d/nginx-organizr-login.conf:/etc/fail2ban/filter.d/nginx-organizr-login.conf:ro
      - /var/log:/var/log:ro
      - ${STACK_CONFIG_DIR}/swag/log/nginx:/swag_logs:ro
      - ${STACK_CONFIG_DIR}/fail2ban/db:/data/db
