services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STACK_CONFIG_DIR}/prowlarr:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`${PROWLARR_TRAEFIK_HOST:-prowlarr}.${TRAEFIK_LOCAL_DOMAIN:-local}`) || Host(`${PROWLARR_TRAEFIK_HOST:-prowlarr}.${HOSTNAME:-homemediaforge}.${TRAEFIK_LOCAL_DOMAIN:-local}`)"
      - "traefik.http.routers.prowlarr.entrypoints=https"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
    depends_on:
      - traefik
    ports:
      - ${PROWLARR_PORT:-9696}:9696
    restart: unless-stopped
    networks:
      homemediaforge_net:
        ipv4_address: ${PROWLARR_IPV4:-172.30.0.25}

networks:
  homemediaforge_net:
    name: ${HOMEMEDIAFORGE_NET_NAME:-homemediaforge_net}
    driver: bridge
    ipam:
      config:
        - subnet: ${HOMEMEDIAFORGE_NET_SUBNET:-172.30.0.0/24}
