services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${WEBUI_PORT}
    volumes:
      - ${STACK_CONFIG_DIR}/qbittorrent:/config
      - ${STACK_DOWNLOADS_DIR_COMPLETED}:/downloads
      - ${STACK_DOWNLOADS_DIR_INCOMPLETED}:/incompleted
      - ${STACK_BLACKHOLE_DIR}:/blackhole
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`${QBITTORRENT_TRAEFIK_HOST:-qbittorrent}.${TRAEFIK_LOCAL_DOMAIN:-local}`)"
      - "traefik.http.routers.qbittorrent.entrypoints=https"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=${WEBUI_PORT:-8080}"
    ports:
      - ${QBITTORRENT_WEBUI_PORT:-8080}:${WEBUI_PORT:-8080}
      - ${QBITTORRENT_BT_PORT:-6881}:6881
      - ${QBITTORRENT_BT_PORT:-6881}:6881/udp
    restart: unless-stopped
    networks:
      homemediaforge_net:
        ipv4_address: ${QBITTORRENT_IPV4:-172.30.0.27}

networks:
  homemediaforge_net:
    name: ${HOMEMEDIAFORGE_NET_NAME:-homemediaforge_net}
    driver: bridge
    ipam:
      config:
        - subnet: ${HOMEMEDIAFORGE_NET_SUBNET:-172.30.0.0/24}
