services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STACK_CONFIG_DIR}/sabnzbd:/config
      - ${STACK_DOWNLOADS_DIR_COMPLETED}:/downloads
      - ${STACK_DOWNLOADS_DIR_INCOMPLETED}:/incompleted
    ports:
      - ${SABNZBD_HTTP_PORT:-8080}:8080
      - ${SABNZBD_HTTPS_PORT:-9090}:9090
    restart: unless-stopped
    networks:
      homemediaforge_net:
        ipv4_address: ${SABNZBD_IPV4:-172.30.0.28}

networks:
  homemediaforge_net:
    name: ${HOMEMEDIAFORGE_NET_NAME:-homemediaforge_net}
    driver: bridge
    ipam:
      config:
        - subnet: ${HOMEMEDIAFORGE_NET_SUBNET:-172.30.0.0/24}
