# ===================================================================
# 🌐 HOME MEDIA FORGE - NETWORK CORE MODULE
# ---------------------------------------------------
# Este módulo crea un “bridge DNS interno” y servicios
# de descubrimiento mDNS/LLMNR para resolver *.local
# en Windows, Linux y macOS sin modificar el router.
# ===================================================================

services:
  # ---------------------------------------------------
  # 🧠 DNS BRIDGE (dnsmasq)
  # ---------------------------------------------------
  dnsbridge:
    image: jpillora/dnsmasq:latest
    container_name: dnsbridge
    hostname: dnsbridge
    network_mode: host # Escucha en el host para UDP/TCP 53
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      TZ: ${TZ:-America/Santiago}
    volumes:
      - ${STACK_CONFIG_DIR}/dnsmasq:/etc/dnsmasq.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--no-resolv"
      - "--domain-needed"
      - "--bogus-priv"
      - "--local=/local/"
      - "--expand-hosts"
      - "--conf-dir=/etc/dnsmasq.d/,*.conf"
      - "--listen-address=0.0.0.0"
      - "--addn-hosts=/etc/dnsmasq.d/99-containers.conf"
      - "--server=1.1.1.1"
      - "--server=8.8.8.8"
      - "--address=/.local/127.0.0.1"
    healthcheck:
      test: ["CMD", "dig", "@127.0.0.1", "localhost"]
      interval: 60s
      timeout: 5s
      retries: 3
    labels:
      - "hmf.module=network"
      - "hmf.description=Internal DNS bridge for .local resolution"

  # ---------------------------------------------------
  # 🧩 DOCKER SERVICE WATCHER
  # ---------------------------------------------------
  dnswatcher:
    image: jwilder/docker-gen
    container_name: dnswatcher
    hostname: dnswatcher
    depends_on:
      - dnsbridge
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${STACK_CONFIG_DIR}/dnsmasq:/etc/dnsmasq.d
      - ${STACK_CONFIG_DIR}/dnsmasq/dnsmasq.template:/etc/dnsmasq.d/dnsmasq.template:ro
    command: >
      -notify-sighup dnsbridge
      -watch /etc/dnsmasq.d/dnsmasq.template
      /etc/dnsmasq.d/99-containers.conf
    labels:
      - "hmf.module=network"
      - "hmf.description=Auto-registro de contenedores en DNS"

  # ---------------------------------------------------
  # 📣 mDNS REFLECTOR / AVAHI
  # ---------------------------------------------------
  avahi:
    build:
      context: /opt/HomeMediaForge/modules/admin
      dockerfile: avahi.Dockerfile
    container_name: avahi
    hostname: avahi
    network_mode: host
    restart: unless-stopped
    volumes:
      - ${STACK_CONFIG_DIR}/avahi:/etc/avahi/services
    labels:
      - "hmf.module=network"
      - "hmf.description=Multicast DNS reflector for local discovery"

  # ---------------------------------------------------
  # 💬 LLMNR / NETBIOS RESPONDER (para Windows)
  # ---------------------------------------------------
  nbns:
    build:
      context: /opt/HomeMediaForge/modules/admin
      dockerfile: responder.Dockerfile
    container_name: nbns
    hostname: nbns
    network_mode: host
    environment:
      - NET_IFACE=${NETWORK_INTERFACE:-enp0s3}
    restart: unless-stopped
    labels:
      - "hmf.module=network"
      - "hmf.description=Responder for Windows NetBIOS/LLMNR discovery"

  # ---------------------------------------------------
  # 🚦 TRAEFIK LOCAL PROXY (con certificados autofirmados)
  # ---------------------------------------------------
traefik:
  image: traefik:${TRAEFIK_VERSION:-v3.1}
  container_name: traefik
  hostname: traefik
  network_mode: host
  restart: unless-stopped
  environment:
    TZ: ${TZ:-America/Santiago}
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ${STACK_CONFIG_DIR}/traefik:/etc/traefik
    - ${STACK_CONFIG_DIR}/traefik/certs:/certs
    - ${STACK_CONFIG_DIR}/traefik/dynamic:/etc/traefik/dynamic
  command:
    # 🧠 Proveedores
    - "--providers.docker=true"
    - "--providers.docker.watch=true"
    - "--providers.docker.exposedbydefault=false"
    - "--providers.docker.useBindPortIP=${TRAEFIK_USE_BIND_PORT_IP:-true}"
    - "--providers.file.directory=/etc/traefik/dynamic"
    - "--providers.file.watch=true"

    # 🌐 Entrypoints
    - "--entrypoints.http.address=:${TRAEFIK_HTTP_PORT:-80}"
    - "--entrypoints.https.address=:${TRAEFIK_HTTPS_PORT:-443}"

    # 🔁 Redirección HTTP → HTTPS
    - "--entrypoints.http.http.redirections.entrypoint.to=https"
    - "--entrypoints.http.http.redirections.entrypoint.scheme=https"

    # 🔒 Habilitar TLS en HTTPS
    - "--entrypoints.https.http.tls=true"

    # 🧰 Dashboard y ping
    - "--api.dashboard=${TRAEFIK_API_DASHBOARD:-true}"
    - "--ping=true"
    - "--ping.entryPoint=http"

    # 🪵 Logging
    - "--log.level=${TRAEFIK_LOG_LEVEL:-INFO}"

    # ⚙️ Seguridad y certificados
    - "--serversTransport.insecureSkipVerify=${TRAEFIK_INSECURE_SKIP_VERIFY:-true}"

  healthcheck:
    test: ["CMD", "traefik", "healthcheck", "--ping"]
    interval: 30s
    timeout: 5s
    retries: 3

  labels:
    - "hmf.module=network"
    - "hmf.description=Reverse proxy HTTPS autofirmado"
