services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    volumes:
      - ${STACK_STORAGE_ROOT_DIR}:/srv
      - ${STACK_CONFIG_DIR}/filebrowser/db/filebrowser.db:/database.db
      - ${STACK_CONFIG_DIR}/filebrowser/.filebrowser.json:/filebrowser.json
    ports:
      - ${FILEBROWSER_PORT:-8081}:80
    networks:
      homemediaforge_net:
        ipv4_address: 172.30.0.13

networks:
  homemediaforge_net:
    name: homemediaforge_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
