services:
  organizr:
    image: organizr/organizr
    container_name: organizr
    hostname: organizr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STACK_CONFIG_DIR}/organizr:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.organizr.rule=Host(`${ORGANIZR_TRAEFIK_HOST:-organizr}.${TRAEFIK_LOCAL_DOMAIN:-local}`)"
      - "traefik.http.routers.organizr.entrypoints=https"
      - "traefik.http.services.organizr.loadbalancer.server.port=80"
    depends_on:
      - traefik
    ports:
      - 5050:80
    restart: unless-stopped
    networks:
      homemediaforge_net:
        ipv4_address: ${ORGANIZR_IPV4:-172.30.0.15}

networks:
  homemediaforge_net:
    name: ${HOMEMEDIAFORGE_NET_NAME:-homemediaforge_net}
    driver: bridge
    ipam:
      config:
        - subnet: ${HOMEMEDIAFORGE_NET_SUBNET:-172.30.0.0/24}
