services:
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    hostname: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${URL}
      - SUBDOMAINS=${SUBDOMAINS}
      - VALIDATION=${VALIDATION}
      - DNSPLUGIN=${DNSPLUGIN}
      - EMAIL=${EMAIL}
      - STAGING=${STAGING}
      - PROPAGATION=${PROPAGATION}
    volumes:
      - ${STACK_CONFIG_DIR}/swag:/config
    labels:
      - "traefik.enable=${SWAG_TRAEFIK_ENABLE:-false}"
      - "traefik.http.routers.swag.rule=Host(`${SWAG_TRAEFIK_HOST:-swag}.${TRAEFIK_LOCAL_DOMAIN:-local}`)"
      - "traefik.http.routers.swag.entrypoints=https"
      - "traefik.http.services.swag.loadbalancer.server.port=443"
      - "traefik.http.services.swag.loadbalancer.server.scheme=${SWAG_TRAEFIK_SCHEME:-https}"
    depends_on:
      - traefik
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
      homemediaforge_net:
        ipv4_address: ${SWAG_IPV4:-172.30.0.17}

networks:
  homemediaforge_net:
    name: ${HOMEMEDIAFORGE_NET_NAME:-homemediaforge_net}
    driver: bridge
    ipam:
      config:
        - subnet: ${HOMEMEDIAFORGE_NET_SUBNET:-172.30.0.0/24}
