services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    hostname: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STACK_CONFIG_DIR}/tautulli:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.rule=Host(`${TAUTULLI_TRAEFIK_HOST:-tautulli}.${TRAEFIK_LOCAL_DOMAIN:-local}`)"
      - "traefik.http.routers.tautulli.entrypoints=https"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"
    ports:
      - ${TAUTULLI_PORT:-8181}:8181
    restart: unless-stopped
    networks:
      homemediaforge_net:
        ipv4_address: ${TAUTULLI_IPV4:-172.30.0.18}

networks:
  homemediaforge_net:
    name: ${HOMEMEDIAFORGE_NET_NAME:-homemediaforge_net}
    driver: bridge
    ipam:
      config:
        - subnet: ${HOMEMEDIAFORGE_NET_SUBNET:-172.30.0.0/24}
