services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STACK_CONFIG_DIR}/tautulli:/config
    ports:
      - ${TAUTULLI_PORT:-8181}:8181
    restart: unless-stopped
    networks:
      homemediaforge_net:
        ipv4_address: 172.30.0.18

networks:
  homemediaforge_net:
    name: homemediaforge_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
