# networks:
  # media:
    # external: true
    # name: media_net
    # driver: bridge
    # attachable: true

services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STACK_CONFIG_DIR}/tautulli:/config
    ports:
      - ${TAUTULLI_PORT:-8181}:8181
    restart: unless-stopped
    # networks:
      # - monitoring
      # - media
