services:
  ofelia:
    image: mcuadros/ofelia:0.3
    container_name: ofelia
    hostname: ofelia
    command: daemon --docker
    environment:
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ${STACK_CONFIG_DIR}/ofelia/logs:/var/log
    labels:
      ofelia.job-exec.plextraktsync.schedule: "0 0,12 * * *"
      ofelia.job-exec.plextraktsync.container: "plextraktsync"
      ofelia.job-exec.plextraktsync.command: "plextraktsync sync"
    logging:
      driver: json-file
      options:
        max-size: "10m" # Tamaño máximo del log (10 MB)
        max-file: "3" # Retiene 3 archivos rotados
    restart: unless-stopped
    networks:
      homemediaforge_net:
        ipv4_address: ${OFELIA_IPV4:-172.30.0.19}

networks:
  homemediaforge_net:
    name: ${HOMEMEDIAFORGE_NET_NAME:-homemediaforge_net}
    driver: bridge
    ipam:
      config:
        - subnet: ${HOMEMEDIAFORGE_NET_SUBNET:-172.30.0.0/24}
