services:
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync
    command: watch
    container_name: plextraktsync
    volumes:
      - ${STACK_CONFIG_DIR}/plextraktsync:/app/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
    networks:
      homemediaforge_net:
        ipv4_address: 172.30.0.20

networks:
  homemediaforge_net:
    name: homemediaforge_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
