services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    hostname: recyclarr
    volumes:
      - ${STACK_CONFIG_DIR}/recyclarr:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
    networks:
      homemediaforge_net:
        ipv4_address: ${RECYCLARR_IPV4:-172.30.0.21}

networks:
  homemediaforge_net:
    name: ${HOMEMEDIAFORGE_NET_NAME:-homemediaforge_net}
    driver: bridge
    ipam:
      config:
        - subnet: ${HOMEMEDIAFORGE_NET_SUBNET:-172.30.0.0/24}
