networks:
  media:
    external: true
    name: media_net
    driver: bridge
    attachable: true
services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STACK_CONFIG_DIR}/rslsync:/config
      - ${STACK_FILES_DIR}/Sync_Data:/downloads
      - ${STACK_FILES_DIR}/Sync_Data:/sync
    restart: unless-stopped
    networks:
      - media
