services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${STACK_CONFIG_DIR}/rslsync:/config
      - ${STACK_FILES_DIR}/Sync_Data:/downloads
      - ${STACK_FILES_DIR}/Sync_Data:/sync
    ports:
      - ${RESILIO_WEBUI_PORT:-8888}:8888
      - ${RESILIO_LISTEN_PORT:-55555}:55555
      - ${RESILIO_LISTEN_PORT:-55555}:55555/udp
    restart: unless-stopped
    networks:
      homemediaforge_net:
        ipv4_address: 172.30.0.22

networks:
  homemediaforge_net:
    name: homemediaforge_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
