services:
  immich:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich
    hostname: immich
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
      traefik:
        condition: service_started
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE_NAME=immich
      - DB_HOST=database
      - DB_PORT=5432
      - REDIS_URL={REDIS_URL}
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES}
    volumes:
      - ${STACK_MEDIA_ROUTE_PHOTOS}:/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`${IMMICH_TRAEFIK_HOST:-immich}.${TRAEFIK_LOCAL_DOMAIN:-local}`) || Host(`${IMMICH_TRAEFIK_HOST:-immich}.${HOSTNAME:-homemediaforge}.${TRAEFIK_LOCAL_DOMAIN:-local}`)"
      - "traefik.http.routers.immich.entrypoints=https"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
    ports:
      - "2283:2283"
    networks:
      homemediaforge_net:
        ipv4_address: ${IMMICH_APP_IPV4:-172.30.0.31}

networks:
  homemediaforge_net:
    name: ${HOMEMEDIAFORGE_NET_NAME:-homemediaforge_net}
    driver: bridge
    ipam:
      config:
        - subnet: ${HOMEMEDIAFORGE_NET_SUBNET:-172.30.0.0/24}
