services:
  redis:
    image: docker.io/valkey/valkey:8-bookworm
    container_name: redis
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    networks:
      homemediaforge_net:
        ipv4_address: 172.30.0.32

networks:
  homemediaforge_net:
    name: homemediaforge_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
