services:
  redis:
    image: docker.io/valkey/valkey:8-bookworm
    container_name: redis
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    networks:
      homemediaforge_net:
        ipv4_address: ${IMMICH_REDIS_IPV4:-172.30.0.32}

networks:
  homemediaforge_net:
    name: ${HOMEMEDIAFORGE_NET_NAME:-homemediaforge_net}
    driver: bridge
    ipam:
      config:
        - subnet: ${HOMEMEDIAFORGE_NET_SUBNET:-172.30.0.0/24}
